name: flutter_study2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  font_awesome_flutter: ^8.0.1
  path_provider: ^0.4.1
  cached_network_image: ^0.5.0+1
  transparent_image: ^0.1.0
  english_words: ^3.1.4
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.1
  flutter_webview_plugin: ^0.3.0+2
  sqflite: ^0.12.2+1
  scoped_model: ^0.3.0
  rxdart: ^0.19.0
  # redux: ^3.0.0
  flutter_redux: ^0.5.2
  location: ^1.4.1
  flutter_flux: ^4.1.3
  battery: ^0.2.3
  connectivity: ^0.3.2
  device_info: ^0.3.0
  web_socket_channel: ^1.0.9
  json_annotation: ^2.0.0
  rx_command: ^4.0.2
  rx_widgets: ^2.2.0
  video_player: ^0.7.2
  flutter_i18n: ^0.5.0
  dartea: ^0.6.1
  shaded_text:
    path: ../shaded_text
  example_plugin:
    path: ../example_plugin

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/images/wallpaper-1.jpg
    - assets/images/wallpaper-2.jpg
    - assets/images/wallpaper-3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts: 
  - family: SnackerComic
    fonts: 
      - asset: assets/fonts/3270Narrow.ttf

  - family: FiraCode
    fonts:
      - asset: assets/fonts/Monofur for Powerline.ttf
      - asset: assets/fonts/Monofur Bold for Powerline.ttf
        weight: 900
      - asset: assets/fonts/Monofur Bold for Powerline.ttf
        weight: 400
      - asset: assets/fonts/Monofur Italic for Powerline.ttf
        style: italic